name: places
description: A Flutter project for Surf course.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dart_code_metrics: ^4.13.0
  dio: ^4.0.6
  elementary: ^1.3.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  mwwm: ^2.0.0
  provider: ^6.0.2
  relation: ^3.1.0
  rxdart: ^0.27.3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - res/
    - res/images/
  fonts:
     - family: Roboto
       fonts:
         - asset: res/fonts/Roboto-Black.ttf
         - asset: res/fonts/Roboto-BlackItalic.ttf
         - asset: res/fonts/Roboto-Bold.ttf
         - asset: res/fonts/Roboto-BoldItalic.ttf
         - asset: res/fonts/Roboto-Light.ttf
         - asset: res/fonts/Roboto-LightItalic.ttf
         - asset: res/fonts/Roboto-Medium.ttf
         - asset: res/fonts/Roboto-MediumItalic.ttf
         - asset: res/fonts/Roboto-Regular.ttf
         - asset: res/fonts/Roboto-Thin.ttf
         - asset: res/fonts/Roboto-ThinItalic.ttf
