name: places
description: A Flutter project for Surf course.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_code_metrics: ^4.13.0
  dio: ^4.0.6
  drift: ^1.6.0
  elementary: ^1.3.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  geolocator: ^8.2.1
  http_parser: ^4.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  map_launcher: ^2.2.3
  mime: ^1.0.2
  path: ^1.8.1
  path_provider: ^2.0.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.0
  yandex_mapkit: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: ^1.6.0
  flutter_launcher_icons: ^0.9.3
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter_icons:
  image_path: "res/images/launch_icon_dev.png"
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - res/
    - res/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Black.ttf
        - asset: res/fonts/Roboto-BlackItalic.ttf
        - asset: res/fonts/Roboto-Bold.ttf
        - asset: res/fonts/Roboto-BoldItalic.ttf
        - asset: res/fonts/Roboto-Light.ttf
        - asset: res/fonts/Roboto-LightItalic.ttf
        - asset: res/fonts/Roboto-Medium.ttf
        - asset: res/fonts/Roboto-MediumItalic.ttf
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Thin.ttf
        - asset: res/fonts/Roboto-ThinItalic.ttf
